Feature/shuffle
BinaryStudioAcademy/bsa-2021-perflow pull request #181
Opened 2021-08-25 08:58 UTC by Den313

Added ability to shuffle music in song queue.

2021-08-25 12:46 UTC, k-r-s-n-v requested changes

2021-08-25 12:46 UTC, k-r-s-n-v commented on frontend/src/app/modules/main-content-container/music-components/queue/queue.component.ts
> +        let currentIndex = this.songs.length; let
Declare one variable per line

2021-08-25 12:46 UTC, k-r-s-n-v commented on frontend/src/app/modules/main-content-container/music-components/queue/queue.component.ts
> +        }
Move the logic to a separate function

2021-08-26 08:35 UTC, proskurnicha approved these changes

2021-08-26 08:35 UTC, merged