Feature/create main component
BinaryStudioAcademy/bsa-2021-perflow pull request #20
Opened 2021-08-02 12:32 UTC by sleepergoose

Create a main component
Combine left-side menu and main page (with Khrapal Maksym)

2021-08-02 12:40 UTC, k-r-s-n-v requested changes

2021-08-02 12:40 UTC, k-r-s-n-v commented on frontend/src/app/moduls/main/cards/calm-rhythms-card/calm-rhythms-card.component.sass
> +    background:#282F37
Add space

2021-08-02 12:40 UTC, k-r-s-n-v commented on frontend/src/app/moduls/main/cards/calm-rhythms-card/calm-rhythms-card.component.sass
> +            background: linear-gradient(180deg, #FD8427 0%, #FD6831 100%)
This gradient is duplicated five times in this pull request. Use variables

2021-08-02 12:40 UTC, k-r-s-n-v commented on frontend/src/app/moduls/main/main-home/main-home.component.ts
> +  scroll = (id: string): void => {
There's no need to explicitly write return type. TS compiler understands the type in 99% of cases

2021-08-02 14:06 UTC, sleepergoose commented
Fixed the review notes and used variables wherever possible

2021-08-02 19:07 UTC, sleepergoose commented
I'm really sorry! Since I forgot to make the profile menu a separate component, I included it in this pull request.

2021-08-03 07:40 UTC, k-r-s-n-v approved these changes

2021-08-03 10:21 UTC, merged