Feature/main constructor
BinaryStudioAcademy/bsa-2021-perflow pull request #243
Opened 2021-09-01 19:12 UTC by Den313

Added main constructor functionality. This feature allows moderators to create containers, where they can customize main page view by adding, deleting sections, their names and entitites, placed in this sections, choose if recently played (Your mix) section(s) needed to show or not. System can have many containers, but only one of them can be published and result of publishing will be shown in main page.

2021-09-01 20:04 UTC, sleepergoose requested changes

2021-09-01 20:04 UTC, sleepergoose commented on frontend/src/app/modules/main/cards/constructor-container-card/constructor-container-card/constructor-container-card.component.ts
> +    this._constructorService.publishContainer(this.container).subscribe();
There is a subscription without unsubscribing. Use takeUntil, take and so on `this._constructorService.publishContainer(this.container).subscribe()`

2021-09-01 20:04 UTC, sleepergoose commented on frontend/src/app/modules/main/cards/constructor-container-card/constructor-container-card/constructor-container-card.component.ts
> +    this._constructorService.deleteContainer(this.container.id).subscribe(
Also there is a subscription without unsubscribing. 
`this._constructorService.deleteContainer(this.container.id).subscribe`

2021-09-01 20:10 UTC, sleepergoose commented on frontend/src/app/modules/main/main-home/main-home.component.ts
> +    this._constructorService.getPublishedContainer().subscribe(
Unsubscribing needs. Something like `.pipe(takeUntil(this._unsubscribe$))`

2021-09-01 20:19 UTC, sleepergoose commented on frontend/src/app/modules/perflow-studio/constructor/containers-page/containers-page/containers-page.component.ts
> +    this._constructorService.getAllContainersViews().subscribe(
There is a subscription without unsubscribing.

2021-09-01 20:27 UTC, sleepergoose requested changes

2021-09-01 20:27 UTC, sleepergoose commented on frontend/src/app/modules/perflow-studio/constructor/create-edit-container/create-edit-container/create-edit-container.component.ts
> +    this._constructorService.getContainer(this._id!).subscribe(
There is a subscription without unsubscribing.

2021-09-01 20:27 UTC, sleepergoose commented on frontend/src/app/modules/perflow-studio/constructor/create-edit-container/create-edit-container/create-edit-container.component.ts
> +      this._constructorService.updateContainer(this.container).subscribe(
There is a subscription without unsubscribing.

2021-09-01 20:27 UTC, sleepergoose commented on frontend/src/app/modules/perflow-studio/constructor/create-edit-container/create-edit-container/create-edit-container.component.ts
> +      this._constructorService.createContainer(this.container).subscribe(
And here

2021-09-01 20:27 UTC, sleepergoose commented on frontend/src/app/modules/perflow-studio/perflow-studio-routing.module.ts
> +  // canActivateChild: [PerflowStudioGuard],
Is a comment line necessary?

2021-09-02 08:46 UTC, proskurnicha commented
Please fix conflicts and comments

2021-09-02 11:58 UTC, proskurnicha approved these changes

2021-09-02 12:02 UTC, merged