Feature/songs list component
BinaryStudioAcademy/bsa-2021-perflow pull request #27
Opened 2021-08-04 12:29 UTC by krolebord

2021-08-04 17:44 UTC, proskurnicha requested changes

2021-08-04 17:44 UTC, proskurnicha commented on frontend/src/app/helpers/sort-compare-functions.ts
> +
Violates B12 point from 
https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md

2021-08-04 18:01 UTC, krolebord commented on frontend/src/app/helpers/sort-compare-functions.ts
> +
Fixed

2021-08-05 07:25 UTC, proskurnicha approved these changes

2021-08-05 07:25 UTC, merged