Feature/load albums from backend, edit ocelot api ports and routes
BinaryStudioAcademy/bsa-2021-perflow pull request #28
Opened 2021-08-04 12:35 UTC by Den313

Implemented loading albums (new-releases) from database. Also edited Ocelot API routing.

2021-08-04 18:05 UTC, proskurnicha requested changes

2021-08-04 18:05 UTC, proskurnicha commented on frontend/src/app/moduls/main/main-home/main-home.component.ts
>    getCalmRhythms = (): Array<object> => new Array<object>();
Using takeUntil(this._unsubscribe$)
But ngOnDestroy not implemented

2021-08-04 18:05 UTC, proskurnicha commented on backend/Perflow/Services/AlbumsService.cs
> +        }
We've already had a global exception handler, is it works?

2021-08-04 18:05 UTC, proskurnicha commented on backend/Perflow/Startup.cs
> +                .WithOrigins("http://localhost:4200"));
Transfer hardcoded "http://localhost:4200" to appsettings.json

2021-08-04 18:05 UTC, proskurnicha commented on backend/Perflow/Services/AlbumsService.cs
> +                albumDTO.Id = 0;
Why do we need it?

2021-08-05 07:44 UTC, k-r-s-n-v approved these changes

2021-08-05 07:44 UTC, k-r-s-n-v commented on backend/Perflow/Common/DTO/Album/AlbumViewDTO.cs
> +        public bool isSingle { get; set; }
Property names should use PascalCase

2021-08-05 07:44 UTC, k-r-s-n-v requested changes
Needs fixes

2021-08-06 07:04 UTC, k-r-s-n-v approved these changes

2021-08-06 07:04 UTC, merged