Add package-lock to .gitignore
BinaryStudioAcademy/bsa-2021-perflow pull request #29
Opened 2021-08-04 15:28 UTC by krolebord

2021-08-04 17:49 UTC, proskurnicha requested changes

2021-08-04 17:49 UTC, proskurnicha commented on frontend/.gitignore
> +package-lock.json
We've already set in package-lock=false .npmrc

So we don't need these changes
(Hopefully that no one will commit this file again)

2021-08-04 17:59 UTC, krolebord commented on frontend/.gitignore
> +package-lock.json
I know we did, but after the addition of .npmrc package-lock.json was added and deleted a few times, so this change is just to be sure

2021-08-05 07:29 UTC, k-r-s-n-v commented
Needs discussion with @proskurnicha

2021-08-05 07:33 UTC, closed without merging