Add playlists/albums page, add common styles for playlist card
BinaryStudioAcademy/bsa-2021-perflow pull request #35
Opened 2021-08-05 16:12 UTC by Slawisch

2021-08-07 09:49 UTC, proskurnicha requested changes

2021-08-07 09:49 UTC, proskurnicha commented on backend/Perflow/Migrations/20210803162535_RunSeeding.cs
> +
We don't need a migration for seeding. As I know there is a script for seeding.
Ask @krolebord more about it.

2021-08-07 09:49 UTC, proskurnicha commented on backend/Perflow/Migrations/20210805133743_AlbumReactionSeed.cs
> +}
We definitely don't need 3 different files with migrations.

2021-08-07 09:49 UTC, proskurnicha commented on backend/Perflow/Services/Implementations/AlbumReactionService.cs
> +        }
Use Return Early Pattern
https://medium.com/swlh/return-early-pattern-3d18a41bba8

2021-08-07 09:49 UTC, proskurnicha commented on backend/Perflow/Services/Implementations/AlbumReactionService.cs
> +        }
And here

2021-08-07 09:49 UTC, proskurnicha commented on backend/Perflow/Services/Implementations/ArtistReactionService.cs
> +            }
here and in the next places

2021-08-07 09:49 UTC, proskurnicha commented on frontend/src/app/services/reaction.service.ts
> +    return response;
I would say that you don't need to assign results to const, you could just return. Here and above in methods

2021-08-08 11:01 UTC, k-r-s-n-v requested changes
Update your previous pull request and then this one and most of the comments will be gone. Next time try to avoid merging branches in a new one because it's different to review what you really changed in the pull request since it contains a lot of the code from different branch

2021-08-08 11:01 UTC, NikitaKrasnovSW commented on backend/Perflow/Common/DTO/Users/UserReadDTO.cs
> +        public string Salt { get; set; }
Remove Password and Salt from dto

2021-08-08 11:01 UTC, k-r-s-n-v commented on backend/Perflow/DataAccess/Context/ModelBuilderExtensions.cs
> +            Seed(modelBuilder);
Delete seeding and seeding migrations

2021-08-08 13:17 UTC, Slawisch commented
I've fixed all of problems from previous pull request and this one only in this branch. So, all changes exist in this branch. Previous ('artist-list') I can delete.

2021-08-08 19:55 UTC, proskurnicha approved these changes

2021-08-08 19:56 UTC, merged