Feature/create page for creating editing playlist
BinaryStudioAcademy/bsa-2021-perflow pull request #40
Opened 2021-08-07 06:32 UTC by sleepergoose

Created a component to create/edit playlist.
by route '/playlists/create' can reach create functionality
by route '/playlists/edit/id' can reach edit functionality

2021-08-07 10:32 UTC, proskurnicha requested changes

2021-08-07 10:32 UTC, proskurnicha commented on backend/Perflow/Services/Implementations/PlaylistService.cs
> +                .FirstOrDefaultAsync();
Where + FirstOrDefaultAsync could change to
FirstOrDefaultAsync(p => p.PlaylistId == playlistSongDTO.PlaylistId && p.SongId == playlistSongDTO.SongId)

2021-08-07 10:32 UTC, proskurnicha commented on backend/Perflow/Services/Implementations/PlaylistService.cs
> +                .FirstOrDefaultAsync();
Here and everywhere in your changes

2021-08-07 10:32 UTC, proskurnicha commented on frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
> +      this.createPlaylist();
Use spread operator (here we don't need it but for the future) 
this.playlist = {
...this.playlist, 
id: 
name:
and so on
}

2021-08-07 10:32 UTC, proskurnicha commented on frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
> +
Don't change each property separately 
this.playlist = { 
         desc: '',
         iconURL:  editedPlaylist.iconURL,
}

2021-08-07 10:32 UTC, proskurnicha commented on frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
> +            this.playlistSongs.push(song);
use spread, instead of push

2021-08-07 10:32 UTC, proskurnicha commented on frontend/src/app/modules/main/create-edit-playlist/edit-playlist-modal/edit-playlist-modal.component.ts
> +
We could get rid of so many getters (here we have just 4 fields, but imagine if we had 20 fields). Use ngModel
https://angular.io/guide/forms

2021-08-07 16:22 UTC, sleepergoose commented
Fixed review notes and remade form to ngModel

2021-08-08 11:13 UTC, k-r-s-n-v requested changes

2021-08-08 11:13 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/create-edit-playlist/create-edit-playlist/create-edit-playlist.component.ts
> +  ngOnInit() {
Please refactor. Function should not take so many lines of code

2021-08-08 20:08 UTC, proskurnicha approved these changes

2021-08-09 09:08 UTC, merged