Feature/my playlists component combine develop temp
BinaryStudioAcademy/bsa-2021-perflow pull request #41
Opened 2021-08-07 16:18 UTC by Khrapal-Max

Added
1. Routing MyPlaylist
- /All
- /Artist
- /Albums
2. Combine Main-HomeComponent
3. Added layout MyPlaylist
4. Binding button LikedSongs(MyPlaylist) with SongsComponent
5. Added cards:
- album-card
- playlist-card
- song-card
6. Refactoring layout Main-HomeComponent
7. Added function scrolling for rows Main-HomeComponent

2021-08-08 20:24 UTC, proskurnicha approved these changes

2021-08-11 12:38 UTC, k-r-s-n-v requested changes

2021-08-11 12:38 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/cards/playlist-card/playlist-card.component.sass
> +>>>>>>> merge:frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.sass
Delete merge conflicts

2021-08-11 12:38 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/cards/song-card/song-card.component.ts
> +  @Input() podcast! : string;
Fix formatting

2021-08-11 12:38 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/main-home/main-home.component.sass
> +
Delete empty lines

2021-08-11 12:38 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/main-home/main-home.component.ts
> +      const move = 255 * 6;
Move to constant

2021-08-11 12:38 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/main-home/main-home.component.ts
> +      const move = 255 * 6;
Use constant

2021-08-11 12:38 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/playlist/all/all.component.html
> +
Delete commented code

2021-08-11 12:38 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/search/search.component.html
> +  </div>
Fix formatting

2021-08-11 12:38 UTC, k-r-s-n-v commented on frontend/src/app/services/playlists/playlist.service.ts
> +  [x: string]: any;
What is this?

2021-08-11 12:55 UTC, Khrapal-Max commented on frontend/src/app/modules/main/cards/playlist-card/playlist-card.component.sass
> +>>>>>>> merge:frontend/src/app/modules/main/cards/square-info-card/square-info-card.component.sass
Done

2021-08-11 12:57 UTC, Khrapal-Max commented on frontend/src/app/modules/main/cards/song-card/song-card.component.ts
> +  @Input() podcast! : string;
Done

2021-08-11 12:57 UTC, Khrapal-Max commented on frontend/src/app/modules/main/main-home/main-home.component.sass
> +
Done

2021-08-11 12:59 UTC, Khrapal-Max commented on frontend/src/app/modules/main/main-home/main-home.component.ts
> +      const move = 255 * 6;
Done

2021-08-11 13:06 UTC, Khrapal-Max commented on frontend/src/app/modules/main/playlist/all/all.component.html
> +
Done

2021-08-11 13:06 UTC, Khrapal-Max commented on frontend/src/app/modules/main/search/search.component.html
> +  </div>
Done

2021-08-11 13:09 UTC, Khrapal-Max commented on frontend/src/app/services/playlists/playlist.service.ts
> +  [x: string]: any;
I dont know. Removed.

2021-08-11 14:35 UTC, Khrapal-Max commented on frontend/src/app/modules/main/main-home/main-home.component.ts
> +      const move = 255 * 6;
Done

2021-08-11 14:54 UTC, k-r-s-n-v requested changes

2021-08-11 14:54 UTC, k-r-s-n-v commented on frontend/src/app/modules/main/cards/song-card/song-card.component.ts
> +  podcast : string;
Fix formatting

2021-08-11 15:16 UTC, Khrapal-Max commented on frontend/src/app/modules/main/cards/song-card/song-card.component.ts
> +  podcast : string;
Done

2021-08-11 15:32 UTC, k-r-s-n-v approved these changes

2021-08-11 15:33 UTC, merged