Feature/artist redirect on new releases
BinaryStudioAcademy/bsa-2021-perflow pull request #72
Opened 2021-08-12 18:29 UTC by Den313

Added onclick redirection for authors and groups, displayed under new-release view. Additionaly fixed bad songs seed data.

2021-08-12 20:06 UTC, proskurnicha requested changes

2021-08-12 20:06 UTC, proskurnicha commented on backend/Perflow/Common/DTO/Albums/AlbumViewDTO.cs
> +        //public IEnumerable<string> Authors { get; set; }
Delete comment

2021-08-12 20:06 UTC, proskurnicha commented on backend/Perflow/Services/Implementations/AlbumsService.cs
> +                    //Authors = a.Songs.Select((s) => s.AuthorType == Domain.Enums.AuthorType.Artist ? s.Artist.UserName : s.Group.Name).ToList()
Delete comment

2021-08-13 07:13 UTC, k-r-s-n-v approved these changes

2021-08-13 07:13 UTC, merged