Feature/frontend routing and left side menu
BinaryStudioAcademy/bsa-2021-perflow pull request #9
Opened 2021-07-28 23:04 UTC by Khrapal-Max

Created module Auth and Main. Auth is responsible for login verification. Main is responsible for navigation and access to the main components.
Route tree

     - / app
     - / login
     - / menu-nav
         - / menu-home
         - / search
         - / playlist
         - / songs

Added a guard. The layout of the menu has been formed.

2021-07-29 07:33 UTC, k-r-s-n-v requested changes

2021-07-29 07:33 UTC, k-r-s-n-v commented on frontend/angular.json
> +              "./node_modules/@angular/material/prebuilt-themes/pink-bluegrey.css",
What is the reason of using Material? We have Semantic UI

2021-07-29 07:33 UTC, k-r-s-n-v commented on frontend/package.json
> +    "@angular/material": "^12.1.3",
Probably don't need it

2021-07-29 07:33 UTC, k-r-s-n-v commented on frontend/src/app/common/material-components.module.ts
> +import {OverlayModule} from '@angular/cdk/overlay';
Delete Material components

2021-07-29 07:33 UTC, k-r-s-n-v commented on frontend/src/app/guard/auth.guard.ts
> +    const sessionId = 123456789;
Delete hard coded value. If this is a workaround, then write it correctly without extra code

2021-07-29 07:33 UTC, k-r-s-n-v commented on frontend/src/app/moduls/auth/landingpage/landingpage.component.ts
> +  }
Add new line

2021-07-29 07:33 UTC, k-r-s-n-v commented on frontend/src/app/moduls/main/main-menu/main-menu.component.html
> +</div>
Replace markdown with Semantic

2021-07-29 07:33 UTC, k-r-s-n-v commented on frontend/src/app/services/auth.service.ts
> +      delay(1000),
If this is not a real code, leave TODO comment

2021-07-30 03:37 UTC, Khrapal-Max reviewed
Edits made

2021-07-30 03:37 UTC, Khrapal-Max commented on frontend/angular.json
> +              "./node_modules/@angular/material/prebuilt-themes/pink-bluegrey.css",
Done

2021-07-30 03:37 UTC, Khrapal-Max commented on frontend/package.json
> +    "@angular/material": "^12.1.3",
Deleted " @ angular / material " : " ^ 12.1.3 "

2021-07-30 03:37 UTC, Khrapal-Max commented on frontend/src/app/common/material-components.module.ts
> +import {OverlayModule} from '@angular/cdk/overlay';
Done

2021-07-30 03:37 UTC, Khrapal-Max commented on frontend/src/app/moduls/auth/landingpage/landingpage.component.ts
> +  }
Done

2021-07-30 03:37 UTC, Khrapal-Max commented on frontend/src/app/services/auth.service.ts
> +      delay(1000),
Done.

Added in service
// TODO: Temporary service to simulate authorization and test routing. Remove after installing the correct authorization system.

2021-07-30 03:37 UTC, Khrapal-Max commented on frontend/src/app/guard/auth.guard.ts
> +    const sessionId = 123456789;
Done.
Added TODO for method checkLogin
// TODO: Temporary body in metod.
  // After adding the token based authorization. 
  // Here, in the verification condition, replace the request for the authorization service - token verification.

2021-07-30 03:37 UTC, Khrapal-Max commented on frontend/src/app/moduls/main/main-menu/main-menu.component.html
> +</div>
Done

2021-07-30 06:52 UTC, k-r-s-n-v approved these changes

2021-07-30 09:47 UTC, merged