Load top 20 by likes artists/songs in user profile
BinaryStudioAcademy/bsa-2021-perflow pull request #96
Opened 2021-08-14 11:55 UTC by JekiXD

2021-08-15 18:28 UTC, proskurnicha requested changes

2021-08-15 18:28 UTC, proskurnicha commented on frontend/src/app/modules/main/user-profile/user-profile.component.ts
>    }
Rename it to getTopArtists, getTopSongs

2021-08-15 18:28 UTC, proskurnicha commented on frontend/src/app/modules/main/user-profile/user-profile.component.ts
> +      (result) => {
Move to const 20 (magic value)

2021-08-15 18:28 UTC, proskurnicha commented on frontend/src/app/modules/main/user-profile/user-profile.component.ts
> +    grid?.scrollBy({ left: this.getGridScrollWidth(selector) * 3, behavior: 'smooth' });
3 to const

2021-08-15 18:28 UTC, proskurnicha commented on frontend/src/app/modules/main/user-profile/user-profile.component.ts
> +    const elementWidth = parseInt(style.gridTemplateColumns.split(' ')[0], 10);
10 to const

2021-08-16 11:32 UTC, k-r-s-n-v requested changes

2021-08-16 11:32 UTC, k-r-s-n-v commented on backend/ApiGateway/ApiGateway/configuration.Production.json
> +      "DownstreamScheme": "https",
Change to http

2021-08-16 11:32 UTC, k-r-s-n-v commented on backend/ApiGateway/ApiGateway/configuration.Production.json
> +      "DownstreamScheme": "https",
Change to http

2021-08-17 08:05 UTC, merged